version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
  nats:
    image: nats:2
    command: ["-js"]
    restart: unless-stopped
    ports: ["4222:4222","8222:8222"]
volumes:
  mongo_data: {}
